// <auto-generated />
using System;
using LMS.WebAPI.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.WebAPI.Migrations
{
    [DbContext(typeof(LMSDBContext))]
    [Migration("20240828001249_maintain-review-relation")]
    partial class maintainreviewrelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.WebAPI.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Bethel Hoppe",
                            CategoryId = 2,
                            CoverImage = "https://picsum.photos/640/480/?image=720",
                            Description = "Aliquid nemo ad beatae labore at dignissimos eius consequatur. Quis minima voluptatum voluptates. Impedit ducimus dolorum beatae mollitia in. Eaque ullam nihil mollitia in. Itaque vel et similique et facere aliquid. Culpa odit qui.",
                            ISBN = "2145553863868",
                            IsAvailable = true,
                            PageCount = 396,
                            PublicationDate = new DateTime(2024, 8, 27, 17, 39, 18, 369, DateTimeKind.Local).AddTicks(1520),
                            Publisher = "Barrows and Sons",
                            Title = "Handmade Rubber Gloves"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Theron Vandervort",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=777",
                            Description = "Commodi eveniet dolorem qui non consequuntur ad expedita repellat porro. Repellat maiores minus sit. Labore aperiam error corporis qui quia. Unde cumque velit non.",
                            ISBN = "4574309328913",
                            IsAvailable = true,
                            PageCount = 978,
                            PublicationDate = new DateTime(2016, 2, 12, 6, 5, 40, 390, DateTimeKind.Local).AddTicks(5883),
                            Publisher = "Kulas Inc",
                            Title = "Rustic Frozen Chair"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Jaquan Hackett",
                            CategoryId = 3,
                            CoverImage = "https://picsum.photos/640/480/?image=363",
                            Description = "Quae at esse et veniam vel amet laboriosam voluptas maiores. Eveniet quod vero aut perferendis quasi minima deleniti. Qui quo dolorem qui quo voluptate dolore alias.",
                            ISBN = "5789810487335",
                            IsAvailable = true,
                            PageCount = 840,
                            PublicationDate = new DateTime(2016, 4, 12, 8, 26, 18, 398, DateTimeKind.Local).AddTicks(2121),
                            Publisher = "Langosh - Reynolds",
                            Title = "Handcrafted Concrete Cheese"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Carol Gutkowski",
                            CategoryId = 4,
                            CoverImage = "https://picsum.photos/640/480/?image=498",
                            Description = "Dolorem voluptatum voluptate. Voluptates explicabo optio mollitia occaecati. Vel facere cupiditate perspiciatis quis voluptas ad aut.",
                            ISBN = "5730864913059",
                            IsAvailable = true,
                            PageCount = 496,
                            PublicationDate = new DateTime(2020, 3, 6, 8, 38, 7, 947, DateTimeKind.Local).AddTicks(2531),
                            Publisher = "Kertzmann Group",
                            Title = "Gorgeous Steel Cheese"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Blaze Bartell",
                            CategoryId = 3,
                            CoverImage = "https://picsum.photos/640/480/?image=983",
                            Description = "Alias et saepe vero quaerat rerum quidem recusandae. At dolorem veritatis. Et quia autem dolores. Aspernatur vel repellendus est minima voluptate. Veniam fugit rerum architecto perferendis perspiciatis itaque velit rerum recusandae.",
                            ISBN = "2970585096089",
                            IsAvailable = true,
                            PageCount = 533,
                            PublicationDate = new DateTime(2021, 6, 21, 6, 5, 22, 884, DateTimeKind.Local).AddTicks(2885),
                            Publisher = "Parisian - Grant",
                            Title = "Refined Concrete Chicken"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Arnold King",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=906",
                            Description = "Dignissimos distinctio minima nisi. Quaerat voluptatem aut consectetur voluptate saepe numquam nisi sed non. Omnis ad dolores at.",
                            ISBN = "4050797655651",
                            IsAvailable = true,
                            PageCount = 187,
                            PublicationDate = new DateTime(2015, 5, 25, 22, 34, 31, 53, DateTimeKind.Local).AddTicks(4620),
                            Publisher = "Rodriguez, Lakin and Lubowitz",
                            Title = "Ergonomic Rubber Tuna"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Myrtis Kulas",
                            CategoryId = 3,
                            CoverImage = "https://picsum.photos/640/480/?image=318",
                            Description = "Aut sequi qui quod officiis ab beatae. Incidunt consequuntur rem delectus recusandae itaque ducimus. Omnis impedit nesciunt possimus occaecati. Qui ut voluptatem voluptatem eum aut voluptatum saepe sequi sit. Accusantium sed rerum consectetur aut occaecati voluptas qui ipsa.",
                            ISBN = "8971316743962",
                            IsAvailable = true,
                            PageCount = 718,
                            PublicationDate = new DateTime(2016, 5, 30, 0, 23, 11, 71, DateTimeKind.Local).AddTicks(4974),
                            Publisher = "McDermott, Wintheiser and Witting",
                            Title = "Refined Metal Ball"
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Luciano Hoeger",
                            CategoryId = 3,
                            CoverImage = "https://picsum.photos/640/480/?image=815",
                            Description = "Magni sunt atque. Fuga voluptas non sint praesentium nesciunt aperiam exercitationem. Quae officia ducimus sint molestiae atque quaerat similique inventore neque. Consectetur quos neque in. Natus voluptatum qui aspernatur accusamus repudiandae sit ex.",
                            ISBN = "6338989967576",
                            IsAvailable = true,
                            PageCount = 230,
                            PublicationDate = new DateTime(2016, 6, 25, 7, 15, 39, 563, DateTimeKind.Local).AddTicks(642),
                            Publisher = "Ryan, Jacobs and DuBuque",
                            Title = "Fantastic Cotton Salad"
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Stella Cremin",
                            CategoryId = 5,
                            CoverImage = "https://picsum.photos/640/480/?image=364",
                            Description = "At architecto nemo rerum est fuga eligendi. Natus eum sit. Ex voluptatem sunt illum. Et vel vel dolores. Magni est dicta. Tempore esse blanditiis porro et quos repudiandae quis.",
                            ISBN = "6666371679128",
                            IsAvailable = true,
                            PageCount = 176,
                            PublicationDate = new DateTime(2021, 3, 20, 18, 42, 16, 25, DateTimeKind.Local).AddTicks(4674),
                            Publisher = "Rosenbaum Inc",
                            Title = "Handmade Cotton Mouse"
                        },
                        new
                        {
                            BookId = 10,
                            Author = "Kay Zemlak",
                            CategoryId = 3,
                            CoverImage = "https://picsum.photos/640/480/?image=494",
                            Description = "Recusandae similique qui quam. Et commodi dolor voluptatem molestias. Enim laboriosam eaque necessitatibus temporibus et voluptas repellendus eligendi. Earum et voluptate quia temporibus eveniet aliquid. Animi laboriosam eum eaque et. Eos et neque id porro aut.",
                            ISBN = "8093810520914",
                            IsAvailable = true,
                            PageCount = 799,
                            PublicationDate = new DateTime(2024, 5, 23, 14, 26, 26, 787, DateTimeKind.Local).AddTicks(1839),
                            Publisher = "Batz, Jaskolski and Herman",
                            Title = "Unbranded Frozen Chips"
                        },
                        new
                        {
                            BookId = 11,
                            Author = "Haskell Schoen",
                            CategoryId = 4,
                            CoverImage = "https://picsum.photos/640/480/?image=686",
                            Description = "Cumque itaque in cupiditate. Autem eveniet omnis deleniti quo necessitatibus et illum nobis. Molestiae facere magni ullam dignissimos maiores sed molestias quam quia. Non incidunt molestias ut.",
                            ISBN = "7968238024690",
                            IsAvailable = true,
                            PageCount = 884,
                            PublicationDate = new DateTime(2015, 4, 28, 2, 57, 57, 704, DateTimeKind.Local).AddTicks(1891),
                            Publisher = "Shanahan - Mueller",
                            Title = "Incredible Plastic Bike"
                        },
                        new
                        {
                            BookId = 12,
                            Author = "Martina Streich",
                            CategoryId = 5,
                            CoverImage = "https://picsum.photos/640/480/?image=791",
                            Description = "Culpa repellat magni quia sit aut quisquam vero. Consequatur sit fuga aut. Ea et sint atque dolorem. Ex est pariatur est voluptas ea velit. Fugit inventore exercitationem et magnam molestiae optio quia.",
                            ISBN = "5700877211343",
                            IsAvailable = true,
                            PageCount = 803,
                            PublicationDate = new DateTime(2023, 2, 21, 1, 33, 25, 898, DateTimeKind.Local).AddTicks(6580),
                            Publisher = "Maggio Inc",
                            Title = "Handcrafted Plastic Chicken"
                        },
                        new
                        {
                            BookId = 13,
                            Author = "Magdalena Schimmel",
                            CategoryId = 3,
                            CoverImage = "https://picsum.photos/640/480/?image=422",
                            Description = "Illum aut eos est fugit occaecati vitae fugit et quia. Soluta tempora nihil velit ipsa consectetur nulla laudantium recusandae. Reprehenderit laboriosam est tempora. Tenetur eligendi saepe quasi sint. Voluptatibus saepe officia autem doloribus aliquam earum tenetur rem. Omnis quo nihil harum qui autem ipsum.",
                            ISBN = "1064706314822",
                            IsAvailable = true,
                            PageCount = 310,
                            PublicationDate = new DateTime(2016, 6, 2, 11, 28, 48, 235, DateTimeKind.Local).AddTicks(807),
                            Publisher = "Lind, Kautzer and Reilly",
                            Title = "Rustic Steel Shoes"
                        },
                        new
                        {
                            BookId = 14,
                            Author = "Ryan Kuphal",
                            CategoryId = 4,
                            CoverImage = "https://picsum.photos/640/480/?image=292",
                            Description = "Sunt ad est dolores inventore occaecati veritatis quia. Eveniet odit mollitia blanditiis voluptas qui harum cupiditate. Et voluptates ex delectus qui nihil aperiam sed qui. Tenetur velit voluptas. Est sint et.",
                            ISBN = "9649416339154",
                            IsAvailable = true,
                            PageCount = 545,
                            PublicationDate = new DateTime(2015, 8, 3, 6, 57, 47, 557, DateTimeKind.Local).AddTicks(9765),
                            Publisher = "Maggio, Rath and Rogahn",
                            Title = "Handcrafted Frozen Table"
                        },
                        new
                        {
                            BookId = 15,
                            Author = "Lily Legros",
                            CategoryId = 4,
                            CoverImage = "https://picsum.photos/640/480/?image=380",
                            Description = "Exercitationem porro et eius odit. Quia sit autem alias. Quam mollitia minus. Ut repellat vitae odio sed asperiores quibusdam iure dolor fugit. Voluptate est sapiente ut voluptas doloribus provident numquam fugit.",
                            ISBN = "2186383723052",
                            IsAvailable = true,
                            PageCount = 418,
                            PublicationDate = new DateTime(2023, 6, 15, 15, 1, 3, 209, DateTimeKind.Local).AddTicks(5130),
                            Publisher = "Bechtelar, Berge and Bode",
                            Title = "Incredible Wooden Pizza"
                        },
                        new
                        {
                            BookId = 16,
                            Author = "Amira Lang",
                            CategoryId = 4,
                            CoverImage = "https://picsum.photos/640/480/?image=468",
                            Description = "Illum est a et itaque sit numquam voluptatibus voluptatum repellendus. Quia delectus quas nihil. Aperiam et a. Tempore delectus non facilis animi. Tenetur quibusdam sed minus atque. Consequatur doloremque facere ad enim hic molestiae praesentium.",
                            ISBN = "2997044743407",
                            IsAvailable = true,
                            PageCount = 127,
                            PublicationDate = new DateTime(2015, 4, 30, 2, 57, 43, 864, DateTimeKind.Local).AddTicks(3405),
                            Publisher = "Senger - Jakubowski",
                            Title = "Tasty Cotton Computer"
                        },
                        new
                        {
                            BookId = 17,
                            Author = "Juliet Runolfsson",
                            CategoryId = 5,
                            CoverImage = "https://picsum.photos/640/480/?image=267",
                            Description = "Quod et sapiente voluptates itaque quas eos sapiente omnis non. Eaque aliquid dolorem nesciunt est in officia alias eveniet delectus. Ullam dignissimos quibusdam veritatis aut. Neque nesciunt qui commodi alias maiores. Et deserunt accusantium consequatur.",
                            ISBN = "9920124488014",
                            IsAvailable = true,
                            PageCount = 567,
                            PublicationDate = new DateTime(2019, 4, 20, 1, 12, 10, 157, DateTimeKind.Local).AddTicks(5289),
                            Publisher = "Koepp LLC",
                            Title = "Gorgeous Steel Ball"
                        },
                        new
                        {
                            BookId = 18,
                            Author = "Braden Hyatt",
                            CategoryId = 4,
                            CoverImage = "https://picsum.photos/640/480/?image=298",
                            Description = "Iure voluptas aliquam sapiente. Autem hic repellendus aut voluptate cum ipsa nulla dolores soluta. Veniam vel dolores. Provident quis dolorem natus accusamus quis et recusandae eum corrupti. Non dolores qui rerum molestias illo natus dolores qui. Esse temporibus corporis dignissimos possimus at.",
                            ISBN = "4486832404814",
                            IsAvailable = true,
                            PageCount = 302,
                            PublicationDate = new DateTime(2017, 9, 19, 12, 3, 40, 565, DateTimeKind.Local).AddTicks(4928),
                            Publisher = "Schneider and Sons",
                            Title = "Fantastic Soft Tuna"
                        },
                        new
                        {
                            BookId = 19,
                            Author = "Kaylin Harber",
                            CategoryId = 4,
                            CoverImage = "https://picsum.photos/640/480/?image=281",
                            Description = "Tenetur aut ipsum. Et dolorem quo at eos ut. Laborum illum ullam sequi. Possimus mollitia voluptatem quod quibusdam sunt. Deserunt quisquam labore nam reprehenderit impedit repellendus et iusto. Nisi et nisi quo vel voluptatem quae.",
                            ISBN = "5648445294780",
                            IsAvailable = true,
                            PageCount = 928,
                            PublicationDate = new DateTime(2019, 5, 13, 18, 7, 26, 428, DateTimeKind.Local).AddTicks(5717),
                            Publisher = "Schamberger, Jacobson and Koepp",
                            Title = "Handcrafted Cotton Chicken"
                        },
                        new
                        {
                            BookId = 20,
                            Author = "Kayli Keebler",
                            CategoryId = 4,
                            CoverImage = "https://picsum.photos/640/480/?image=441",
                            Description = "Suscipit tempore ut quae commodi non in quisquam voluptatem. Sit autem et aut vero omnis dicta maiores. Facere aliquam nostrum velit officia. Qui dolore numquam aut in architecto. Quia fugiat quia cum.",
                            ISBN = "8814306288626",
                            IsAvailable = true,
                            PageCount = 881,
                            PublicationDate = new DateTime(2018, 5, 13, 0, 30, 1, 831, DateTimeKind.Local).AddTicks(4907),
                            Publisher = "Bechtelar Inc",
                            Title = "Small Wooden Bike"
                        });
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Outdoors"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Beauty"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Clothing"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Home"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Industrial"
                        });
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Checkout", b =>
                {
                    b.Property<int>("CheckoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckoutId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckoutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CheckoutId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Checkouts");
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReviewId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "664ac092-f0f8-4e8f-96a2-14a3eaf7e99b",
                            Name = "Librarian",
                            NormalizedName = "LIBRARIAN"
                        },
                        new
                        {
                            Id = "a2656152-deb0-4622-9bfe-38c29b86ddb4",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Book", b =>
                {
                    b.HasOne("LMS.WebAPI.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Checkout", b =>
                {
                    b.HasOne("LMS.WebAPI.Entities.Book", "Book")
                        .WithMany("Checkouts")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.WebAPI.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Review", b =>
                {
                    b.HasOne("LMS.WebAPI.Entities.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.WebAPI.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LMS.WebAPI.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LMS.WebAPI.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.WebAPI.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LMS.WebAPI.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Book", b =>
                {
                    b.Navigation("Checkouts");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
