// <auto-generated />
using System;
using LMS.WebAPI.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.WebAPI.Migrations
{
    [DbContext(typeof(LMSDBContext))]
    [Migration("20240826215122_book-category-data-seeder")]
    partial class bookcategorydataseeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.WebAPI.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Queen Rogahn",
                            CategoryId = 2,
                            CoverImage = "https://picsum.photos/640/480/?image=140",
                            Description = "Ut tenetur ipsam architecto commodi et. Delectus atque quia qui. Cumque fugiat nisi quibusdam a placeat omnis maxime aliquid labore. Aut sit natus consequatur animi magnam expedita dolorem nostrum.",
                            ISBN = "9350118348800",
                            IsAvailable = true,
                            PageCount = 374,
                            PublicationDate = new DateTime(2018, 8, 13, 23, 54, 50, 388, DateTimeKind.Local).AddTicks(3690),
                            Publisher = "Goldner Group",
                            Title = "Small Cotton Car"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Briana Boehm",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=577",
                            Description = "Odio atque enim labore sunt nostrum minima. Id omnis voluptas non natus molestias animi deserunt rerum. Qui tenetur laudantium rem fugit recusandae accusantium non sint. Alias recusandae qui illo id.",
                            ISBN = "2104547867664",
                            IsAvailable = true,
                            PageCount = 692,
                            PublicationDate = new DateTime(2015, 5, 11, 13, 55, 53, 809, DateTimeKind.Local).AddTicks(432),
                            Publisher = "Bruen - Mills",
                            Title = "Refined Cotton Ball"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Shayna Ondricka",
                            CategoryId = 2,
                            CoverImage = "https://picsum.photos/640/480/?image=223",
                            Description = "Placeat et quia sint repellendus incidunt. Odit rem temporibus eaque. Voluptates velit incidunt commodi ut minima ut.",
                            ISBN = "5870284705275",
                            IsAvailable = true,
                            PageCount = 205,
                            PublicationDate = new DateTime(2016, 3, 27, 5, 6, 11, 322, DateTimeKind.Local).AddTicks(6683),
                            Publisher = "Dare, Leffler and Crona",
                            Title = "Handcrafted Soft Soap"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Alivia Berge",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=872",
                            Description = "Vel et officiis ab commodi dolores tenetur quisquam ut. Eligendi consequatur fuga cupiditate quibusdam vero. Fugiat totam omnis quidem voluptatibus et vel. Dolor voluptatum at animi.",
                            ISBN = "2339462428304",
                            IsAvailable = true,
                            PageCount = 147,
                            PublicationDate = new DateTime(2016, 8, 10, 22, 55, 16, 282, DateTimeKind.Local).AddTicks(6901),
                            Publisher = "West - Kirlin",
                            Title = "Incredible Fresh Shoes"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Sabina Hackett",
                            CategoryId = 5,
                            CoverImage = "https://picsum.photos/640/480/?image=352",
                            Description = "Qui consequatur in quibusdam ab. Consequatur earum aperiam sint dolore facilis sit adipisci quos. Illum non quia non enim eveniet. Fugit eaque ducimus dolores nobis qui molestiae et quia. Modi fugiat facilis consectetur non mollitia consequatur saepe veritatis rerum.",
                            ISBN = "6273916832391",
                            IsAvailable = true,
                            PageCount = 873,
                            PublicationDate = new DateTime(2015, 10, 13, 1, 46, 0, 141, DateTimeKind.Local).AddTicks(8910),
                            Publisher = "Pfeffer and Sons",
                            Title = "Fantastic Plastic Gloves"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Destini Pfeffer",
                            CategoryId = 3,
                            CoverImage = "https://picsum.photos/640/480/?image=805",
                            Description = "Ratione odio assumenda cumque provident id sint temporibus. Et ratione ea enim. Nihil et unde eveniet rerum distinctio enim.",
                            ISBN = "4033777687828",
                            IsAvailable = true,
                            PageCount = 937,
                            PublicationDate = new DateTime(2022, 11, 15, 0, 34, 56, 461, DateTimeKind.Local).AddTicks(6070),
                            Publisher = "Zemlak - O'Conner",
                            Title = "Sleek Plastic Table"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Alexie Goldner",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=484",
                            Description = "Quae vitae est repellendus cupiditate laboriosam aliquam quod. Sit labore praesentium. Odio dolorem tempora aut fuga repellat. Reprehenderit in omnis dicta placeat suscipit maxime. Autem vel et. Enim dolorem laborum quibusdam necessitatibus possimus.",
                            ISBN = "7194093216011",
                            IsAvailable = true,
                            PageCount = 183,
                            PublicationDate = new DateTime(2016, 5, 5, 3, 24, 17, 438, DateTimeKind.Local).AddTicks(3938),
                            Publisher = "Fadel - Kuhic",
                            Title = "Handmade Plastic Hat"
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Glen Cassin",
                            CategoryId = 5,
                            CoverImage = "https://picsum.photos/640/480/?image=247",
                            Description = "Sed qui minima rerum molestiae. Dolorem vel voluptatem vitae quia. Ullam doloremque ut magni odit ad laborum rem sunt.",
                            ISBN = "1216253695514",
                            IsAvailable = true,
                            PageCount = 887,
                            PublicationDate = new DateTime(2017, 9, 13, 14, 4, 30, 101, DateTimeKind.Local).AddTicks(7315),
                            Publisher = "Larkin - Conroy",
                            Title = "Practical Plastic Fish"
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Megane Hartmann",
                            CategoryId = 5,
                            CoverImage = "https://picsum.photos/640/480/?image=960",
                            Description = "Tenetur consequuntur itaque eaque repellendus rerum eius autem neque ad. Perferendis adipisci sed sit assumenda adipisci. Quidem culpa facere et cupiditate deserunt alias debitis sed. Quae nobis aut iste doloremque. Sapiente voluptatem illum sunt voluptate sed odit sint. Quia quia temporibus eligendi.",
                            ISBN = "3282773840510",
                            IsAvailable = true,
                            PageCount = 994,
                            PublicationDate = new DateTime(2014, 10, 11, 3, 11, 50, 507, DateTimeKind.Local).AddTicks(3069),
                            Publisher = "Smitham and Sons",
                            Title = "Gorgeous Soft Computer"
                        },
                        new
                        {
                            BookId = 10,
                            Author = "Khalil Nolan",
                            CategoryId = 2,
                            CoverImage = "https://picsum.photos/640/480/?image=722",
                            Description = "Natus ut sint ut delectus debitis. Eos nisi earum eveniet eum. In accusamus aut magnam fuga laudantium nihil. Veritatis quasi similique porro exercitationem illo quaerat officia. Rerum est consectetur quia et dicta rerum quas. Veritatis ut atque aut dolore porro culpa illum.",
                            ISBN = "2067764841292",
                            IsAvailable = true,
                            PageCount = 600,
                            PublicationDate = new DateTime(2019, 12, 30, 0, 40, 37, 940, DateTimeKind.Local).AddTicks(4281),
                            Publisher = "White and Sons",
                            Title = "Ergonomic Cotton Gloves"
                        },
                        new
                        {
                            BookId = 11,
                            Author = "Christelle Wolff",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=445",
                            Description = "Et ea et blanditiis sunt praesentium. Dolorem non nesciunt dolores labore ab. Quam vel in sed recusandae. Itaque nostrum rerum sunt culpa consectetur. Et ad modi eius optio.",
                            ISBN = "0131498142504",
                            IsAvailable = true,
                            PageCount = 755,
                            PublicationDate = new DateTime(2024, 4, 9, 23, 36, 17, 69, DateTimeKind.Local).AddTicks(6235),
                            Publisher = "Langworth - Marquardt",
                            Title = "Unbranded Plastic Pants"
                        },
                        new
                        {
                            BookId = 12,
                            Author = "Ayla Mayert",
                            CategoryId = 4,
                            CoverImage = "https://picsum.photos/640/480/?image=1053",
                            Description = "Voluptas ipsum et consequatur sit laudantium. Consequuntur atque unde aperiam minima aut veniam corporis earum. Consequatur tenetur perspiciatis vel dolores. Neque ducimus debitis excepturi corrupti dolor quaerat quae dolorem. Iste adipisci beatae quia modi sed eligendi repellendus.",
                            ISBN = "8415390821401",
                            IsAvailable = true,
                            PageCount = 510,
                            PublicationDate = new DateTime(2015, 8, 15, 18, 37, 21, 2, DateTimeKind.Local).AddTicks(9900),
                            Publisher = "Corwin, Lynch and Morissette",
                            Title = "Sleek Fresh Hat"
                        },
                        new
                        {
                            BookId = 13,
                            Author = "Tony Hamill",
                            CategoryId = 5,
                            CoverImage = "https://picsum.photos/640/480/?image=733",
                            Description = "Consequuntur nisi recusandae quasi iure. Cupiditate vitae velit sint et ea tenetur qui a hic. Ad maxime praesentium.",
                            ISBN = "0284972056337",
                            IsAvailable = true,
                            PageCount = 763,
                            PublicationDate = new DateTime(2024, 4, 18, 5, 59, 27, 909, DateTimeKind.Local).AddTicks(6290),
                            Publisher = "Becker and Sons",
                            Title = "Handmade Fresh Table"
                        },
                        new
                        {
                            BookId = 14,
                            Author = "Santiago Wilderman",
                            CategoryId = 4,
                            CoverImage = "https://picsum.photos/640/480/?image=373",
                            Description = "Sed voluptas animi magni aut. Dolorum aliquid molestiae. Beatae totam aperiam. Tempore voluptas rerum ut quo quae. Cupiditate alias ullam. Veritatis cupiditate voluptatum aut eos blanditiis velit nulla.",
                            ISBN = "4207650657608",
                            IsAvailable = true,
                            PageCount = 323,
                            PublicationDate = new DateTime(2023, 1, 26, 16, 3, 59, 268, DateTimeKind.Local).AddTicks(294),
                            Publisher = "Carter, Kuvalis and Homenick",
                            Title = "Generic Metal Soap"
                        },
                        new
                        {
                            BookId = 15,
                            Author = "Kelsie Morissette",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=548",
                            Description = "In eligendi consequatur minus aspernatur illum praesentium maiores omnis quisquam. Iste esse excepturi sint suscipit. Debitis illo rem possimus voluptas enim et est sit rerum. Quam corporis voluptatem beatae aut quibusdam. In et sed aut.",
                            ISBN = "0651729368195",
                            IsAvailable = true,
                            PageCount = 364,
                            PublicationDate = new DateTime(2024, 6, 18, 11, 56, 27, 69, DateTimeKind.Local).AddTicks(5586),
                            Publisher = "Heidenreich, Flatley and Dickinson",
                            Title = "Licensed Soft Sausages"
                        },
                        new
                        {
                            BookId = 16,
                            Author = "Julian Mueller",
                            CategoryId = 5,
                            CoverImage = "https://picsum.photos/640/480/?image=850",
                            Description = "Veniam asperiores ipsum eos provident aliquam quo. Aut eos sequi omnis quia. Natus id voluptatum. Non suscipit porro.",
                            ISBN = "8383304368307",
                            IsAvailable = true,
                            PageCount = 330,
                            PublicationDate = new DateTime(2019, 11, 21, 22, 23, 54, 924, DateTimeKind.Local).AddTicks(8134),
                            Publisher = "Douglas - Gerhold",
                            Title = "Small Fresh Shoes"
                        },
                        new
                        {
                            BookId = 17,
                            Author = "Corbin Mohr",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=575",
                            Description = "Alias voluptas voluptatem eveniet quasi temporibus incidunt qui ipsam. Tempore perspiciatis ad quaerat excepturi dolor vero ipsa voluptates. Facere aut fuga inventore sed nesciunt.",
                            ISBN = "2375632473477",
                            IsAvailable = true,
                            PageCount = 120,
                            PublicationDate = new DateTime(2022, 12, 12, 22, 29, 54, 658, DateTimeKind.Local).AddTicks(9171),
                            Publisher = "Gerhold - Ruecker",
                            Title = "Tasty Rubber Chicken"
                        },
                        new
                        {
                            BookId = 18,
                            Author = "Christelle Dietrich",
                            CategoryId = 2,
                            CoverImage = "https://picsum.photos/640/480/?image=945",
                            Description = "Sit consectetur sequi tempora et et delectus. Et reiciendis architecto. Molestias placeat praesentium et ex qui rerum rerum rem. Ab voluptatem quia est porro dolores. Culpa nam molestiae harum dolores eaque delectus.",
                            ISBN = "7818129859842",
                            IsAvailable = true,
                            PageCount = 848,
                            PublicationDate = new DateTime(2017, 7, 24, 1, 33, 42, 598, DateTimeKind.Local).AddTicks(144),
                            Publisher = "Schumm, Stokes and Schmeler",
                            Title = "Licensed Plastic Chicken"
                        },
                        new
                        {
                            BookId = 19,
                            Author = "Sam Weimann",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=55",
                            Description = "Facilis voluptas et. Occaecati quia placeat nesciunt ducimus sed quam quaerat vel. Tenetur expedita neque nihil.",
                            ISBN = "4476011315420",
                            IsAvailable = true,
                            PageCount = 264,
                            PublicationDate = new DateTime(2022, 5, 14, 12, 20, 19, 320, DateTimeKind.Local).AddTicks(6991),
                            Publisher = "Christiansen - Dickinson",
                            Title = "Ergonomic Soft Table"
                        },
                        new
                        {
                            BookId = 20,
                            Author = "Arielle Bins",
                            CategoryId = 5,
                            CoverImage = "https://picsum.photos/640/480/?image=32",
                            Description = "Corrupti nam sapiente dolores. Laboriosam ullam dolorum qui voluptas sit. Minus et illo quo voluptas ad assumenda quo. Magni cum laudantium et. Occaecati atque sint tenetur suscipit id aut eos. Aut eligendi sit libero in aspernatur est.",
                            ISBN = "8572156043672",
                            IsAvailable = true,
                            PageCount = 595,
                            PublicationDate = new DateTime(2017, 3, 17, 4, 42, 7, 935, DateTimeKind.Local).AddTicks(1967),
                            Publisher = "Johnston, Lemke and Weimann",
                            Title = "Practical Steel Mouse"
                        });
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Tools"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Baby"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Grocery"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Grocery"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Outdoors"
                        });
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Checkout", b =>
                {
                    b.Property<int>("CheckoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckoutId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckoutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CheckoutId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Checkouts");
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReviewId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3167fd11-1b83-4043-8f00-d12984f6f9a7",
                            Name = "Librarian",
                            NormalizedName = "LIBRARIAN"
                        },
                        new
                        {
                            Id = "ba7b1c19-82d3-4c81-ace7-56b17c591292",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Book", b =>
                {
                    b.HasOne("LMS.WebAPI.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Checkout", b =>
                {
                    b.HasOne("LMS.WebAPI.Entities.Book", "Book")
                        .WithMany("Checkouts")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.WebAPI.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Review", b =>
                {
                    b.HasOne("LMS.WebAPI.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.WebAPI.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LMS.WebAPI.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LMS.WebAPI.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.WebAPI.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LMS.WebAPI.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Book", b =>
                {
                    b.Navigation("Checkouts");
                });

            modelBuilder.Entity("LMS.WebAPI.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
